### ISSUE TITLE
ScreenShot

### ISSUE THREAD

**Issue by KosmosGithub** [AlphaNecron/Void#25]
Can anyone send any screenshot of what VOID Looks like

**Comment by AlphaNecron** [comment]
![image](https://user-images.githubusercontent.com/57827456/162430581-b11dc830-119d-4ba7-9f06-bd8f69ab7657.png)
![image](https://user-images.githubusercontent.com/57827456/162430608-1d29eb3b-d229-4fc7-9a74-387dc90811db.png)
![image](https://user-images.githubusercontent.com/57827456/162430637-632611ab-239f-49b6-9d60-4826a6b50cb8.png)

Ugly right? I'm planning to rewrite `Void` to make it better. This is it now.
![image](https://user-images.githubusercontent.com/57827456/162430720-6c92f257-1813-4677-8c33-d02bae9d445e.png)
